### ISSUE TITLE
Does the Action replace gh-runner-ecs-ec2-stack

### ISSUE THREAD

**Issue by bjorntheart** [PasseiDireto/gh-runner-task-action#6]
Not an issue, but I didn't know how else to reach out to you guys.

I've been preparing an AMI by reading your post here https://aws.amazon.com/pt/blogs/aws-brasil/utilizando-runtimes-customizados-no-amazon-ecs, but I've noticed the repository 
 https://github.com/PasseiDireto/gh-runner-ecs-ec2-stack is now archived. Do you stil make use of using ECS with your own custom EC2 image or does this action replace the need for that?

Sorry for using the issue tracker to ask a question :-)

**Comment by n-neubauer** [comment]
My understanding is as follows: 

- [https://github.com/PasseiDireto/gh-runner](https://github.com/PasseiDireto/gh-runner) is for provisioning an Docker/ECR image that (when run) registers itself as a self-hosted runner with GitHub.  
- [https://github.com/PasseiDireto/gh-runner-ecs-ec2-stack](https://github.com/PasseiDireto/gh-runner-ecs-ec2-stack) configures the infrastructure on the AWS side that will create one (or more) ECS instances via an autoscaling group when a task is run with the given task definition which places the tasks that utilise the above image.  
- Finally, [https://github.com/PasseiDireto/gh-runner-task-action](https://github.com/PasseiDireto/gh-runner-task-action) is used as a GitHub workflow action that will actually call run-task against the configured cluster/task definition.

**Comment by vschettino** [comment]
Hey guys, thanks for reaching out! Sorry the delay, I never got a notification about this issue :(
 @norman-neubauer got the idea precisely :) 

The old [gh-runner-ecs-ec2-stack](https://github.com/PasseiDireto/gh-runner-ecs-ec2-stack) is archived because we came with another infrastructure approach (almost the same but with a few tweaks and Pulumi for IaC) and it is not ready for being open sourced yet. But you can get most of the idea looking the code. Anyway, both the action and the Docker image can be used independently.

**Comment by robsonandradev** [comment]
If some of you guys are running Kubernetes, there is an easy way to use the runner
[https://gist.github.com/RobsonAndraDev/94c87c9c1f909413d3ce5e154a084d5d](https://gist.github.com/RobsonAndraDev/94c87c9c1f909413d3ce5e154a084d5d)
